name: C CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test_package_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt-get install -y gcc make

      - name: Build the C program
        run: make build

      - name: Run Unit Tests
        run: make test

      - name: Package Artifact
        run: |
          mkdir artifact
          cp app artifact/app
          zip -r artifact/build.zip artifact/app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: c-build-artifact
          path: artifact/build.zip

      - name: Simulated Deploy
        env:
          DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
        run: |
          echo "Downloading artifact..."
          echo "Deploying using masked API Key: ${DEPLOY_API_KEY}"
